<?php

namespace AppBundle\Repository;

/**
 * Telefono_ProveedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Telefono_ProveedorRepository extends \Doctrine\ORM\EntityRepository
{
}
