<?php

namespace AppBundle\Repository;

/**
 * TipoUnidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoUnidadRepository extends \Doctrine\ORM\EntityRepository
{
}
